
export const movies = [
 {title:'Spider Noir',date:'May 25, 2026',genre:'Crime • Mystery',rating:'8.8',runtime:'2h 05m',poster:'linear-gradient(160deg,#111,#6b35ff)',tags:['Mystery','Drama']},
 {title:'Beyond the Horizon',date:'May 20, 2026',genre:'Sci-Fi • Adventure',rating:'8.8',runtime:'2h 08m',poster:'linear-gradient(160deg,#101629,#7c3cff 55%,#ff4bd8)',tags:['Fantasy','Adventure']},
 {title:'Northbound',date:'May 25, 2026',genre:'Romance • Comedy',rating:'8.6',runtime:'2h 05m',poster:'linear-gradient(160deg,#10203a,#22d3ee 55%,#ff9d42)',tags:['Romance','Comedy']},
 {title:'Silent Evidence',date:'May 25, 2026',genre:'Thriller • Detective',rating:'8.4',runtime:'1h 58m',poster:'linear-gradient(160deg,#201128,#ff4bd8 50%,#7c3cff)',tags:['Thriller','Crime']},
 {title:'After Midnight',date:'May 25, 2026',genre:'Drama • Horror',rating:'8.2',runtime:'2h 02m',poster:'linear-gradient(160deg,#050505,#7c3cff 50%,#111827)',tags:['Horror','Drama']},
 {title:'Kitty',date:'April 25, 2026',genre:'Comedy • Family',rating:'8.1',runtime:'1h 46m',poster:'linear-gradient(160deg,#311044,#ff9d42 55%,#ff4bd8)',tags:['Comedy','Family']},
 {title:'Noir',date:'May 15, 2026',genre:'Action • Noir',rating:'8.0',runtime:'2h 05m',poster:'linear-gradient(160deg,#070707,#1f2937 55%,#22d3ee)',tags:['Action','Noir']},
 {title:'Final Match',date:'June 02, 2026',genre:'Adventure • Comedy',rating:'7.9',runtime:'2h 01m',poster:'linear-gradient(160deg,#172554,#7c3cff,#22d3ee)',tags:['Adventure','Comedy']}
];
export const cast = ['Nicolas Cage / Ben Reilly','Randy Oglesby / Chief McNamara','Richard Robichaux / Walters','Treisa Gary / Nurse'];
export function slugify(title){ return encodeURIComponent(title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')); }
export function movieBySlug(slug){ const clean=decodeURIComponent(slug||'').toLowerCase(); return movies.find(m=>slugify(m.title)===slug||m.title.toLowerCase()===clean||m.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')===clean) || movies[1]; }
export function posterStyle(m){return `background:${m.poster}`}
export function detailUrl(m){const raw=m.id||m.tmdbId||m.dbMovieId||slugify(m.title);const id=Number.isFinite(Number(raw))?Math.abs(Number(raw)):raw;return m.mediaType==='tv'?`/movie/${id}?type=tv`:`/movie/${id}`}
export function stars(score){ const n=Math.round(Number(score)/2); return '★★★★★'.split('').map((s,i)=>`<span class="${i<n?'on':''}">★</span>`).join('')+` <strong>${score}</strong>`; }
export function makePoster(m){return `<article class="poster-card" data-href="${detailUrl(m)}"><div class="poster-thumb" style="${posterStyle(m)}"></div><div class="poster-card-info"><div class="card-title-row"><h3>${m.title}</h3><span class="movie-card-rating">★ ${m.rating}</span></div><div class="card-date-row"><p>${m.date}</p><span>${m.runtime}</span></div></div></article>`}
export function makeMovie(m){return `<article class="movie-card"><div class="poster-thumb" style="${posterStyle(m)}" data-href="${detailUrl(m)}"></div><div class="card-meta card-info"><div class="card-title-row"><h3>${m.title}</h3><span class="movie-card-rating">★ ${m.rating}</span></div><div class="card-date-row"><p>${m.date}</p><span>${m.runtime}</span></div></div><div class="card-actions"><button data-href="${detailUrl(m)}">View</button><button aria-label="Add to favourites">♡</button></div></article>`}
export function makeMatch(m,i){return `<article class="match-card" data-href="${detailUrl(m)}"><div class="poster-thumb" style="${posterStyle(m)}"></div><div class="match-content"><div class="match-percent">${[94,92,91][i]||90}% match</div><div class="match-title-row"><h3>${m.title}</h3><span class="match-rating">★ ${m.rating}</span></div><p>${m.date}<span style="float:right">${m.runtime}</span></p><p class="profile-line">Recommended because it matches this movie style and your saved preferences.</p><div class="tags">${m.tags.map(t=>`<span>${t}</span>`).join('')}</div></div></article>`}
export function makeRec(m,i){return `<article class="rec-item"><div class="rank">${i+1}</div><div class="poster-thumb" style="${posterStyle(m)}" data-href="${detailUrl(m)}"></div><div><div class="rec-title-row"><h3>${m.title}</h3><span class="rec-rating">★ ${m.rating}</span></div><p>Recommended because it matches your saved genres, ratings and watch history.</p><div class="tags">${m.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="rec-actions"><button data-href="${detailUrl(m)}">View</button><button>Wishlist</button></div></article>`}
export function makeDash(m,status){return `<article class="dash-item" data-href="${detailUrl(m)}"><div class="poster-thumb" style="${posterStyle(m)}"></div><div><strong>${m.title}</strong><p>${m.genre}</p><span class="pill">${m.runtime}</span></div><span class="pill">${status}</span></article>`}
